export const UPDATE_MAIL_LIST = 'UPDATE_MAIL_LIST'

export const SET_UPDATING = 'SET_UPDATING'

export const SET_EMAIL_DETAIL = 'SET_EMAIL_DETAIL'

export const STAR_EMAIL_IN_LIST = 'STAR_EMAIL_IN_LIST'

export const READ_EMAIL_IN_LIST = 'READ_EMAIL_IN_LIST'

export const SET_SENDING_STATUS = 'SET_SENDING_STATUS'

export const SET_SENT_MAIL_LIST = 'SET_SENT_MAIL_LIST'

export const SET_DRAFTS_MAIL_LIST = 'SET_DRAFTS_MAIL_LIST'

export const SET_ADDRESS_LIST = 'SET_ADDRESS_LIST'

export const SET_GROUP_LIST = 'SET_GROUP_LIST'

export const SET_USER = 'SET_USER'

export const SET_SHOW_LOGIN = 'SET_SHOW_LOGIN'

export const MARK_INBOX_EMAIL = 'MARK_INBOX_EMAIL'

export const SET_USER_LIST = 'SET_USER_LIST'

export const SET_UNLOAD_LIST = 'SET_UNLOAD_LIST'
